[project]
name = "ms-with-rabbitmq"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.14",
    "faststream[rabbit]>=0.5.44",
    "uvicorn>=0.35.0",
]
